
export const SUCCESS = "SUCCESS"

export const FAILURE = "FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const ADD_PROFILE = "ADD_PROFILE"

export const REMOVE_PROFILE = "REMOVE_PROFILE"

export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE"

export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT"

export const POPULATE_PROFILE_LIST = "POPULATE_PROFILE_LIST"

export const REMOVE_PROFILE_USER = "REMOVE_PROFILE_USER"

export const UPDATE_PROFILE_USER = "UPDATE_PROFILE_USER"

export const TOGGLE_COLLAPSED = "TOGGLE_COLLAPSED"

